#ifndef APP_CONFIG_MEM_WRITE
#define APP_CONFIG_MEM_WRITE

#include "config.hpp"

#define PROG_FULL_NAME "WinUSB"
#define PROG_FULL_NAME_GETTEXT _("WinUSB")

#define PROG_PKG_NAME PACKAGE
#define PROG_PKG_NAME_GETTEXT _T(PROG_PKG_NAME)

#endif //APP_CONFIG_MEM_WRITE
