.\" winusbgui man page. 
.\" Contact colingille@hotmail.com to correct errors or omissions. 
.TH man 6 "3 October 2010" "1.0" "winusbgui"
.SH NAME
winusbgui \- A graphical interface for wingui.
.SH SYNOPSIS
.\" Syntax goes here. 
.B winusbgui
.SH DESCRIPTION
launches the winusbgui programm. There are no command line switches yet.
.SH AUTHOR
.nf
Colin GILLE / congelli501 (colingille@hotmail.com)
.fi
.SH HISTORY
2011 \- Initial version
