.\" winusb man page. 
.\" Contact colingille@hotmail.com to correct errors or omissions. 
.TH man 6 "3 October 2010" "1.0" "winusb"
.SH NAME
winusb \- A simple command line tool to create Windows Installation's USB stick under Linux.
.SH SYNOPSIS
.\" Syntax goes here. 
.B winusb
.SH DESCRIPTION
launches the winusb programm. There are no command line switches yet.
See winusb --help for more information.
.SH AUTHOR
.nf
Colin GILLE / congelli501 (colingille@hotmail.com)
.fi
.SH HISTORY
2011 \- Initial version
