.TH woeusbgui 1 "@@WOEUSB_VERSION@@" "WoeUSB" "WoeUSB User Manual"
.SH NAME
woeusbgui \- A GUI wrapper for woeusb(1)

.SH SYNOPSIS
.B woeusbgui

.SH DESCRIPTION
This is a GUI wrapper for woeusb(1), currently it only support
.B --device
creation method.
.PP
It is advised to use woeusb(1) instead, as it is more will-maintained and support more creation methods.

.SH OPTIONS
There are no command line options yet.

.SH BUGS
Refer our
.UR https://github.com/slacka/WoeUSB/issues
issue tracker
.UE
 for any known issues
.br

.SH SEE ALSO
woeusb(1)

.SH AUTHORS
Colin GILLE / congelli501 <colingille@hotmail.com>
.br
林博仁 <Buo.Ren.Lin@gmail.com>
