.TH man 6 "3 October 2010" "1.0" "woeusb"
.SH NAME
woeusb \- A simple command line tool to create Windows Installation's USB stick under Linux.
.SH SYNOPSIS
.\" Syntax goes here. 
.B woeusb
.SH DESCRIPTION
This manpage is currently not completed, refer `woeusb --help` for usage of woeusb
.SH AUTHOR
.nf
Colin GILLE / congelli501 (colingille@hotmail.com)
.fi
.SH HISTORY
2011 \- Initial version
