.TH man 6 "3 October 2010" "1.0" "woeusbgui"
.SH NAME
woeusbgui \- A graphical interface for woeusb(1).
.SH SYNOPSIS
.\" Syntax goes here. 
.B woeusbgui
.SH DESCRIPTION
There are no command line switches yet.
.SH AUTHOR
.nf
Colin GILLE / congelli501 (colingille@hotmail.com)
.fi
.SH HISTORY
2011 \- Initial version
